/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Sudoku;

import org.junit.jupiter.api.Test;
import Sudoku.App;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        //assertNotNull();
    }
}

//this file is not needed at all, but since it keeps getting generated i'll keep it here cus i can't get rid of it