/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Sudoku;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.Button;
import javafx.scene.layout.HBox;

public class App {

    public static void main(String[] args) {
        System.out.println("hello");
    }
}

//this file was randomly generated, since this could be useful, i'll keep it around
