/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Java.Sudoku.Project;

import org.junit.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
