/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Java.Sudoku.Project;

import javax.print.attribute.TextSyntax;

import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.scene.*;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.layout.Pane;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.TilePane;
import javafx.scene.paint.Color;
import javafx.scene.shape.Rectangle;
import javafx.stage.Stage;

public class App extends Application{

    //initializations
    Rectangle box_ur;
    Rectangle box_ul;
    Rectangle box_mm;
    Rectangle box_lr;
    Rectangle box_ll;
    Button testButton;
    Node node;
    TextField b11; //creates a text field to enter values in my reaction when i found it afte a week "YES FINALLY I CAN CONTINUE THIS PROJECT"
    TextField b21;
    StackPane testPane;

//https://edencoding.com/javafx-textfield/#:~:text=Validating%20user%20input%201%20TextFormatter%20class.%20If%20you,called%20a%20UnaryOperator.%203%20Testing%20for%20numbers.%20
//dats the tutorial, look over it later or tmr cus im lazy
    
    public Parent createApplication() {


        return new Pane(testButton);
    }
    
    //shows the game window and does stuff with the game window
    @Override
    public void start(Stage stage) throws Exception {

        //sets the background
        TilePane tilePane = new TilePane();
        tilePane.setPrefColumns(3);
        tilePane.setPrefRows(3);
        tilePane.setTileAlignment( Pos.CENTER );

        tilePane.getChildren().addAll(
                new Rectangle( 300, 300, Color.GREY),
                new Rectangle( 300, 300, Color.WHITE ),
                new Rectangle( 300, 300, Color.GREY ),
                new Rectangle( 300, 300, Color.WHITE ),
                new Rectangle( 300, 300, Color.GREY ),
                new Rectangle( 300, 300, Color.WHITE ),
                new Rectangle( 300, 300, Color.GREY ),
                new Rectangle( 300, 300, Color.WHITE ),
                new Rectangle( 300, 300, Color.GREY )
        );

        testPane.getChildren().add(b11);
        StackPane testpane = new StackPane();
        //testpane.setFill(Color.LIGHTGRAY);

        //shows the packground
        testpane.getChildren().add(b11);
        stage.setTitle("Sudoku");
        Scene scene = new Scene(testpane);
        stage.setScene( scene ); //try to figure out a way to work around this
        stage.show();
    }

    //runs the script
    public static void main(String[] args) {
        launch(args);
    }

}
